title: Nick Pape
description: Portfolio and blog for dev tooling, AI, and random musings.
theme: just-the-docs

url: https://nickpape.com

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

search_enabled: false
