title: Nick Pape
description: Portfolio and blog for dev tooling, AI, and random musings.
theme: just-the-docs

url: https://nickpape.com

# Disable default aux links
aux_links: null

# Use your custom HTML instead
aux_links_custom: true

search_enabled: false

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "11.9.0"

# Footer content
# Note: This is deprecated. Use _includes/footer_custom.html for more robust content.
footer_content: "© 2024 Nick Pape. Content licensed under <a href=\"https://opensource.org/licenses/MIT\">MIT</a>."

# Footer last edited timestamp
last_edit_timestamp: true
last_edit_time_format: "%b %e, %Y at %I:%M %p"

# Footer "Edit this page on GitHub" link text
gh_edit_link: false

color_scheme: dark

callouts:
  note:
    title: Note
    color: blue
  warning:
    title: Warning
    color: red
  important:
    title: Important
    color: yellow
  highlight:
    title: Highlight
    color: purple
  summary:
    title: Summary
    color: grey-dk

