title: Nick Pape
description: Portfolio and blog for dev tooling, AI, and random musings.
theme: just-the-docs

url: https://nickpape.com

# Aux links for the upper right navigation
aux_links:
  "GitHub":
    - "https://github.com/nick-pape"
  "LinkedIn":
    - "https://www.linkedin.com/in/nickpape-software"
  "Email":
    - "mailto:nick@nickpape.com"

# Makes Aux links open in a new tab
aux_links_new_tab: true

search_enabled: false

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "11.9.0"
